### ISSUE TITLE
The URL path should follow the swagger file stated

### ISSUE THREAD

**Issue by neithnet-markyang** [s0917251664/simple_api#3]
as title:
The URL is specified in swagger file:  
- url: 'http://192.168.0.100/quiz/v1'

**Comment by s0917251664** [comment]
抱歉，太久沒有看到swagger 格式，因此漏看了指定位置，這邊的框架有重新修正路由位置，docker run 時可以把容器對外指向192.168.0.100:80 ，應該會和您的需求相同。
